### ISSUE TITLE
Ajout d'une licence libre

### ISSUE THREAD

**Issue by bzg** [agora-gouv/agora-app#355]
Pour l'instant, le dépôt ne contient pas de licence, donc c'est le [CRPA](https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000031366350/) qui s'applique. Voir [la documentation](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-fais-des-choix-technologique/licences#appliquer-une-licence) pour la licence.

La mission logiciels libres de la DINUM ([code.gouv.fr](https://code.gouv.fr)) est dispo pour aider à choisir une licence si besoin: contact@code.gouv.fr.

**Comment by bzg** [comment]
Est-ce que quelqu'un lit ces issues ?

**Comment by FYHenry** [comment]
# Licence libre en France

Bonjour.

Si ça peut motiver existe une série de licences libres bien adaptées au droit français : CeCILL[^1].

[^1]: Source: [https://cecill.info/index.fr.html](https://cecill.info/index.fr.html)

**Comment by bzg** [comment]
Toujours dispo pour aider si besoin, mais je n'ai pas l'impression que ces issues sont traitées.

**Comment by encalv** [comment]
Hello! Désolé du temps de réponses, il y a eu pas mal de changement dans l'équipe récemment, dispo pour en discuter !

**Comment by bzg** [comment]
Pas de souci ! Peux-tu m'envoyer un mail (bastien.guerry@code.gouv.fr) avec quelques disponibilités entre le 15 et 25 juillet ?  Merci beaucoup !

**Comment by encalv** [comment]
PR : https://github.com/agora-gouv/agora-app/pull/546
